version: '2'

  mcm-client_id-gen:
    container_name: mcm-client_id-gen
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/mcm_paygate_db
      SECRET_KEY: my_super_secret_key
    ports:
      - "8081:8081"

