version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcm_paygate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mcm-client_id-gen:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/mcm_paygate_db
      SECRET_KEY: my_super_secret_key
    ports:
      - "8081:8081"

volumes:
  postgres_data:
